# Generated by Django 4.2.8 on 2023-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyAppMembers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membros",
            name="data_entrada",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="membros",
            name="telefone",
            field=models.IntegerField(null=True),
        ),
    ]
